server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 2000
  ####找不到处理器直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  ####是否为工程中的资源文件建立映射
  resources:
    add-mappings: false

jwt:
  secret: ptSecret
  # 60 * 60
  expiration: 3600
  # 60 * 60 * 24 * 7L
  expiration_remember: 604800
  token_prefix: "Bearer "
  token_header: Authorization
  token_type: JWT
  role_claims: roles

mybatis:
  ###数据库模型对象
  type-aliases-package: com.pt.bloglib.dao.entity
  mapper-locations: mapper/*.xml


###生产坏境设为true，开启swagger-ui
swagger:
  enabled: true

###以下为自定义变量
site:
  introduction: "site testing"
